# Generated by Django 5.0.6 on 2024-06-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
