# Generated by Django 5.0.6 on 2024-06-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_shirt_discount_alter_shirt_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='top',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='shorts',
            name='top',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sneakers',
            name='top',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
